(run-at-time "00:59" 3600 'org-save-all-org-buffers)
(add-to-list 'auto-mode-alist '("\\org\\'" . org-mode))
(setq org-directory "~/Documents/org/")
(setq org-mobile-inbox-for-pull "~/Documents/org/from-mobile.org")
(setq org-mobile-directory "~/Dropbox/MobileOrg")

(setq org-export-latex-classes nil)
(when (require 'org-latex nil t)
  (add-to-list 'org-export-latex-packages-alist '("" "listings"))
  (add-to-list 'org-export-latex-packages-alist '("" "color"))
  (setq org-export-latex-listings t))
(setq org-indent-mode nil)
(setq org-export-html-style
      "<style type=\"text/css\">
 <!--/*--><![CDATA[/*><!--*/
.src {
        background-color: #3f3f3f !important;
        color: #d8d8d8 !important;
        border-color: #1E2320 !important;
        }
  /*]]>*/-->
   </style>")

(add-to-list 'org-export-latex-classes
          '("article"
             "\\documentclass{scrartcl}"
             ("\\section{%s}" . "\\section*{%s}")
             ("\\subsection{%s}" . "\\subsection*{%s}")
             ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
             ("\\paragraph{%s}" . "\\paragraph*{%s}")
             ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))


(add-to-list 'org-export-latex-classes
          '("koma-article"
             "\\documentclass{scrartcl}"
             ("\\section{%s}" . "\\section*{%s}")
             ("\\subsection{%s}" . "\\subsection*{%s}")
             ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
             ("\\paragraph{%s}" . "\\paragraph*{%s}")
             ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))

(add-to-list 'org-export-latex-classes
          '("koma-report"
             "\\documentclass{scrreprt}"
	     ("\\chapter{%s}" . "\\chapter*{%s}")
             ("\\section{%s}" . "\\section*{%s}")
             ("\\subsection{%s}" . "\\subsection*{%s}")
             ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
             ("\\paragraph{%s}" . "\\paragraph*{%s}")))

(add-to-list 'org-export-latex-classes
          '("moderncv"
             "\\documentclass{moderncv}\\moderncvtheme[black]{classic}"
             ("\\section{%s}" . "\\section*{%s}")
             ("\\subsection{%s}" . "\\subsection*{%s}")
             ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
             ("\\paragraph{%s}" . "\\paragraph*{%s}")
             ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))


(setq org-export-html-postamble-format '(
("en" "<p class=\"author\">Author: %a (%e)</p>\n<p class=\"date\">Date: %d</p>\n<p class=\"creator\">Generated by %c</p>\n<p class=\"xhtml-validation\">%v</p><p class=\"licence\">Licencia: <href a=\"http://creativecommons.org/licenses/by-sa/2.5/\">this work is released under the Creative Commons Attribution-ShareAlike 2.5 Generic (CC BY-SA 2.5) Licence\n</href></p>")
("es" "<p class=\"author\">Autor: %a (%e)</p>\n<p class=\"date\">Fecha: %d</p>\n<p class=\"creator\">Generado por %c</p>\n<p class=\"xhtml-validation\">%v</p><p class=\"licence\">Licencia: <href a=\"http://creativecommons.org/licenses/by-sa/2.5/ar\">este trabajo esta liberado bajo la Licencia Atribución-CompartirIgual 2.5 Argentina (CC BY-SA 2.5)\n</href></p>")))

(defun org-export-latex-format-image (path caption label attr &optional shortn)
  "Format the image element, depending on user settings."
  (let (ind floatp wrapp multicolumnp placement figenv)
    (setq floatp (or caption label))
    (setq ind (org-get-text-property-any 0 'original-indentation path))
    (when (and attr (stringp attr))
      (if (string-match "[ \t]*\\<wrap\\>" attr)
	  (setq wrapp t floatp nil attr (replace-match "" t t attr)))
      (if (string-match "[ \t]*\\<float\\>" attr)
	  (setq wrapp nil floatp t attr (replace-match "" t t attr)))
      (if (string-match "[ \t]*\\<multicolumn\\>" attr)
	  (setq multicolumnp t attr (replace-match "" t t attr))))

    (setq placement
	  (cond
	   (wrapp "{l}{0.5\\textwidth}")
	   (floatp (concat "[" org-latex-default-figure-position "]"))
	   (t "")))

    (when (and attr (stringp attr)
	       (string-match "[ \t]*\\<placement=\\(\\S-+\\)" attr))
      (setq placement (match-string 1 attr)
	    attr (replace-match "" t t attr)))
    (setq attr (and attr (org-trim attr)))
    (when (or (not attr) (= (length attr) 0))
      (setq attr (cond (floatp "width=0.7\\textwidth")
		       (wrapp "width=0.48\\textwidth")
		       (t attr))))
    (setq figenv
	  (cond
	   (wrapp "\\begin{wrapfigure}%placement
\\centering
\\includegraphics[%attr]{%path}
\\end{wrapfigure}")
	   (multicolumnp "\\begin{figure*}%placement
\\centering
\\includegraphics[%attr]{%path}
\\end{figure*}")
	   (floatp "\\begin{figure}%placement
\\centering
\\includegraphics[%attr]{%path}
\\end{figure}")
	   (t "\\includegraphics[%attr]{%path}")))


    (setq figenv (mapconcat 'identity (split-string figenv "\n")
			    (save-excursion (beginning-of-line 1)
					    (looking-at "[ \t]*")
					    (concat "\n" (match-string 0)))))

    (if (and (not label) (not caption)
	     (string-match "^\\\\caption{.*\n" figenv))
	(setq figenv (replace-match "" t t figenv)))

    (org-add-props
	(org-fill-template
	 figenv
	 (list (cons "path"
		     (if (file-name-absolute-p path)
			 (expand-file-name path)
		       path))
	       (cons "attr" attr)
	       (cons "shortn" (if shortn (format "[%s]" shortn) ""))
	       (cons "labelcmd" (if label (format "\\label{%s}"
						  label)""))
	       (cons "caption" (or caption ""))
	       (cons "placement" (or placement ""))))
	nil 'original-indentation ind)))

(require 'org-remember)
(add-hook 'org-babel-after-execute-hook 'org-display-inline-images)

(org-babel-do-load-languages
 (quote org-babel-load-languages)
 (quote ((emacs-lisp . t)
         (dot . t)
         (ditaa . t)
         (R . t)
         (python . t)
         (ruby . t)
         (gnuplot . t)
         (clojure . t)
         (sh . t)
         (ledger . t)
         (org . t)
         (plantuml . t)
         (latex . t))))

(setq org-default-notes-file (concat org-directory "/notes.org"))
(setq org-agenda-files (let ((result))
			 (dolist (word '("/TODO.org" "/WORK.org" "/PERSONAL.org" "/w.org" "/notes.org"))
			   (setq result (cons (concat org-directory word) result)))
			 result))
(global-set-key "\C-cr" 'org-remember)
(global-set-key "\C-cl" 'org-store-link)
(global-set-key "\C-ca" 'org-agenda)
(global-set-key "\C-cb" 'org-iswitchb)
(setq org-completion-use-ido t)
(setq org-link-abbrev-alist
      '(("rt" . "https://intranet.fr.smartjog.net/rt/Ticket/Display.html?id=")))

(add-hook 'org-remember-after-finalize-hook 'org-agenda-to-appt) ;; allows agenda items to be added after meeting remember.

(defun xa1/org-remember-finalize ()
  "Finalize the remember process."
  (interactive)
  (unless org-remember-mode
    (error "This does not seem to be a remember buffer for Org-mode"))
  (run-hooks 'org-remember-before-finalize-hook)
  (unless (fboundp 'remember-finalize)
    (defalias 'remember-finalize 'remember-buffer))
  (when (and org-clock-marker
	     (equal (marker-buffer org-clock-marker) (current-buffer)))
    ;; the clock is running in this buffer.
    (when (and (equal (marker-buffer org-clock-marker) (current-buffer))
	       (or (eq org-remember-clock-out-on-exit t)
		   (and org-remember-clock-out-on-exit
			(y-or-n-p "The clock is running in this buffer.  Clock out now? "))))
      (let (org-log-note-clock-out) (org-clock-out))))
  (when buffer-file-name
    (do-auto-save))
  (remember-finalize)
  (run-hooks 'org-remember-after-finalize-hook))

(setq org-todo-keywords
      '((sequence "TODO(t)" "|" "DONE(d!)")
	(sequence "AI(a)" "|" "CLOSED(t!)")
	(seqence  "TEST(T)" "KO(k!)" "|" "OK(o!)")
	(sequence "|" "MEETING(m)")
	(sequence "|" "TOREAD(R)")
	(sequence "REPORT(r)" "BUG(b)" "KNOWNCAUSE(k)" "|" "FIXED(f!)")
	(sequence "|" "CANCELED(c!)")))
(setq org-log-done 'time)
(setq org-log-into-drawer t)
(setq org-remember-templates
      '(("Meeting" ?m "* MEETING %^{Meeting Date and Time}T%? %:subject\n:PROPERTIES:\n:LOCATION: %^{Location}\n:END:\n %i\n %a" (concat org-directory "/WORK.org") "Meetings")
	("Todo" ?t "* TODO %?\n  %i\n  %a" (concat org-directory "/TODO.org") "Tasks")
	("Journal" ?j "* %U %?\n\n  %i\n  %a" (concat org-directory "/JOURNAL.org"))
	("Idea" ?i "* %^{Title}\n  %i\n  %a" (concat org-directory "/JOURNAL.org") "New Ideas")))

(setq org-icalendar-store-UID t)
(setq org-clock-persist 'history)
(when (require 'org-clock nil t)
  (org-clock-persistence-insinuate))

(setq org-src-fontify-natively t)
(add-hook 'org-mode-hook 'turn-on-font-lock)  ; org-mode buffers only
(add-hook 'org-mode-hook 'org-indent-mode)    ; org-mode buffers only
(add-hook 'mail-mode-hook 'turn-on-orgstruct++)
;;(add-hook 'mail-mode-hook 'turn-on-orgstruct)
(add-hook 'mail-mode-hook 'turn-on-orgtbl++)
(setq org-agenda-include-diary t)
(add-hook 'org-agenda-mode-hook '(lambda () (hl-line-mode 1)))

(when (require 'appt nil t) ;; from http://article.gmane.org/gmane.emacs.orgmode/5271
  (add-hook 'diary-display-hook 'diary-fancy-display)
  (setq appt-time-msg-list nil)
  (setq appt-display-format 'echo)
  (setq appt-display-mode-line t)
  (setq appt-message-warning-time 120)
  (org-agenda-to-appt)

  (defadvice  org-agenda-redo (after org-agenda-redo-add-appts)
    "Pressing `r' on the agenda will also add appointments."
    (progn
      (setq appt-time-msg-list nil)
      (org-agenda-to-appt)))

  (ad-activate 'org-agenda-redo)
  (appt-activate 1))

(provide 'xa1-org)
