#!/bin/sh

ssh xaiki.net "cd Mail && git add . && git commit -sm 'autocommit pre-sync (remote) `date`'"
cd ~/Mail && git add . && git commit -asm "autocommit pre-sync (local) `date`"
cd ~/Mail && git pull --rebase
cd ~/Mail && git push && ssh xaiki.net "cd Mail && git reset --hard && git clean -f"


