#! /bin/zsh

test -f ~/.env && . ~/.env

export EMAIL="xaiki@evilgiggle.com"
export FULLNAME="Niv Sardi"

export DEBEMAIL="xaiki@debian.org"
export DEBFULLNAME=$FULLNAME

#export GTI_AUTHOR_NAME=$FULLNAME
#export GIT_COMMITTER_NAME=$FULLNAME
#export GIT_AUTHOR_EMAIL=$DEBEMAIL
#export GIT_COMMITTER_EMAIL=$DEBEMAIL

if which colormake > /dev/null; then
	export MAKE=colormake
fi

if which emacsclient.emacs-snapshot > /dev/null; then
	export EMACS_FLAVOUR=.emacs-snapshot;
fi

#export LANG=`echo $LANG | sed s/utf8/UTF8/`
export CVS_RSH="ssh"
export MANWIDTH=80
export EDITOR="env TMPDIR=/tmp emacsclient${EMACS_FLAVOUR} -a nano"
export VISUAL="env TMPDIR=/tmp emacsclient${EMACS_FLAVOUR} -a nano"
export CCACHE_DIR=$HOME/.ccache

export RLWRAP_HOME=~/.cache/rlwrap/
export GTK_IM_MODULE=xim

export LC_MESSAGES=C
export LC_ALL=

export HOME=`readlink -f $HOME`

if [[ "$TERM" == "dumb" ]]
then
  unsetopt zle
  unsetopt prompt_cr
  unsetopt prompt_subst
  unfunction precmd
  unfunction preexec
  PS1='$ '
fi
